### ISSUE TITLE
ReaderManager.ListAvailableReadersAsync - .Net 7 - MAUI

### ISSUE THREAD

**Issue by Gogzs** [TechnologySolutionsUkLtd/ascii-protocol#11]
We're currently evaluating upgrading our app to .Net 7, but we're running into issues with invoking ReaderManager.ListAvailableReadersAsync(), it returns 0 available readers.

Target Android Framework for .Net 7 MAUI is API33, which requires adding android.permission.BLUETOOTH_CONNECT.

With all that set, we're still not able to get any available reader through the ReaderManager. We're using the latest Tsl.ASCIIProtocol.Std 1.6.0. nuget package.

As always, thanks for the amazing support.

**Comment by robinTsl** [comment]
We have just published this nuget package to comply with the latest Android OS updates. The required changes are noted in the release notes for the package, but we will be publishing refreshed SDK samples shortly to correspond with this update showing how to obtain the permissions from the user in the app.

version 1.6.0
     - built for Android TargetFramework v12 (API level 31).
       When targeting Android 12+ (API31+), the following permissions must be obtained at runtime:
         Manifest.Permission.BluetoothConnect
         Manifest.Permission.BluetoothScan
       Until these permissions are obtained, the Bluetooth enumerator will return an empty list.

**Comment by shawyunz** [comment]
> We have just published this nuget package to comply with the latest Android OS updates. The required changes are noted in the release notes for the package, but we will be publishing refreshed SDK samples shortly to correspond with this update showing how to obtain the permissions from the user in the app.
> 
> version 1.6.0 - built for Android TargetFramework v12 (API level 31). When targeting Android 12+ (API31+), the following permissions must be obtained at runtime: Manifest.Permission.BluetoothConnect Manifest.Permission.BluetoothScan Until these permissions are obtained, the Bluetooth enumerator will return an empty list.

Hi Robin,
we're also migrating from Xamarin to Maui, but target SDK API30 for now,
using the Nuget package Tsl.AsciiProtocol.Std 1.6.0,
permissions granted as suggested,
only changed from ReaderModelLocator to IServiceCollection in MauiProgram.
And cannot get the reader list from the first page.

Compared to the debug on Xamarin,
TSLReaderManager.TransportsManager_TransportChanged() has never been triggered in Maui.
Already get two values in transportsManager.Enumerators on the main page (AndroidBluetooth and AndroidUsb), but no device return.
Any advice on debugging or any Tsl method to help identify where the issue is?
Thank you.

**Comment by shawyunz** [comment]
@robinTsl 
When tried to call `enumerator.ListAsciiTransportsAsync()`, had a null reference exception in `enumerator.AbortedException`

![image](https://github.com/TechnologySolutionsUkLtd/ascii-protocol/assets/43285754/fbff6fd7-2b98-44d0-bbc1-ac51e687327b)

And only found those in StackTrace:
```
   at TechnologySolutions.Rfid.AsciiProtocol.Platform.BroadcastReceiverRegisteredAction.Register(IntentFilter filter)
   at TechnologySolutions.Rfid.AsciiProtocol.Transport.AsciiTransportEnumeratorAndroidBluetooth.StartWatching(Boolean resumed)
   at TechnologySolutions.Rfid.AsciiProtocol.Platforms.AsciiTransportEnumerator`1.<StartInternal>d__57[[TechnologySolutions.Rfid.AsciiProtocol.Transport.AsciiTransportAndroidBluetooth, TechnologySolutions.Rfid.AsciiProtocol.Connections, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
```
![image](https://github.com/TechnologySolutionsUkLtd/ascii-protocol/assets/43285754/5c5593ce-4857-4908-8f19-175266ff0df5)

Any suggestions?

**Comment by robinTsl** [comment]
Please switch to the TSL.AsciiProtocol package now updated for .NET 8 MAUI
